AppId: "938065556169449472"
SecretId: "VDZiqUPI_EScZlpls26mrk1XzAwsZtkh"
GuildId: "938060820280115230"
Server: "https://discord.com/api/oauth2/authorize?client_id=938065556169449472&permissions=8&scope=bot"
Token : "OTM4MDY1NTU2MTY5NDQ5NDcy.Yfk3oQ.PPGwsFCzAlkFSQ9QaByc5ZrM-fQ"
Msg: "新用户首sssss次发送消息"
